### ISSUE TITLE
Datafetch seems to fail

### ISSUE THREAD

**Issue by daumann** [fbrosda/weather-maps#7]
When running your project, I receive the following errors:
`GET http://localhost:3000/data/cloud.json?resolution=high&forecast=1 net::ERR_CONNECTION_REFUSED`
`GET http://localhost:3000/data/cloud.png?resolution=high&forecast=1 net::ERR_CONNECTION_REFUSED`

The dist/data folder remains empty.

**Comment by fbrosda** [comment]
Hi, could it be that you are missing the 'grib_dump' executable from eccodes? 

I made a small adjustment, to improve the error message, if the binary is missing. This will most likely not fix the problem, but hopefully gives a better hint for the problem.

If you still get the exact same error, could you please add some more information about your setup, as the only way for me to reproduce the errors, was by removing eccodes.
